---

- name: "Create hostgroups"
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_api_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_group: "{{ es_env_host_group }}"
    state: present
  become: no

- name: "Create a new host or update an existing host's info"
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_api_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ es_env_hostname }}"
    host_groups: "{{ es_env_host_group }}"
    link_templates: "{{ es_env_link_templates }}"
    status: enabled
    state: present
    proxy: null
    interfaces: "{{ es_env_interfaces }}"
  changed_when: false
  become: no

- name: "Updating host configuration with macros"
  local_action:
    module: zabbix_hostmacro
    server_url: "{{ zabbix_api_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ es_env_hostname }}"
    macro_name: "{{ item.macro_key }}"
    macro_value: "{{ item.macro_value }}"
  with_items: "{{ es_env_macros | default([]) }}"
  become: no

- name: "Creating map"
  local_action:
    module: template
    dest: /tmp/test_map
    src: zbx_map.j2

- name: Creating maps
  local_action:
    module: zabbix_template
    template: "{{ lookup('template', item) }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    server_url: "{{ zabbix_api_url }}"
  with_items:
    - zbx_map.j2
  changed_when: false
  become: no

